planner_frequency: 10.0  # 3.0

TrajectoryPlannerROS:

  max_vel_x: 1.0  # 3 #1.5 # X 方向最大速度
  min_vel_x: -0.1 # 0.1 X 方向最小速速

  max_vel_y: 1  # 2 # 1 # Y 方向最大速度
  min_vel_y: -1 # Y 方向最小速速

  max_vel_theta:  3.14 # 2.0
  min_vel_theta: -3.14 # 1.0
  min_in_place_vel_theta: 3.14  # 1.0

  acc_lim_x: 1.0  # 2.5 # X 加速限制
  acc_lim_y: 1.0 # 0 #Y 加速限制
  acc_lim_theta: 2.0 # 2.0 # 角速度加速限制

# Goal Tolerance Parameters，目标公差
  xy_goal_tolerance: 0.30  # 0.1
  yaw_goal_tolerance: 0.10  # 0.05

# Differential-drive robot configuration
# 是否是全向移动机器人
  holonomic_robot: true

# Forward Simulation Parameters，前进模拟参数
  sim_time: 0.5  #  0.5  # 2.8
  vx_samples: 18
  vtheta_samples: 20 # 20
  sim_granularity: 0.05
